version: 2
jobs:
  build:
    docker:
      - image: circleci/android:api-28-alpha
    steps:
      - checkout
      - run:
          name: Create google-services.json
          command: |
            echo $GOOGLESERVICES_BASE64 | base64 --decode > app/google-services.json
      - run:
          name: Build debug APK
          command: |
            ./gradlew :app:assembleDebug
