name: Android CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: set up JDK 1.8git
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Create google-services.json from secrets
      env: # Or as an environment variable
        GOOGLE_SERVICES_JSON: ${{ secrets.GOOGLE_SERVICES_JSON }}
      run: echo $GOOGLE_SERVICES_JSON | base64 --decode - > app/google-services.json
    - name: Build with Gradle
      run: ./gradlew build
